In [22]:
import pandas

In [23]:
movies = pandas.read_csv("movies_small.csv", sep = ";")

In [24]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,190000000,"[{""id"": 28, ""name"": ""Action""}]",http://www.furious7.com/,168259,"[{""id"": 830, ""name"": ""car race""}, {""id"": 3428,...",en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,102.322217,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}, {""iso_...",2015-04-01,1506249360,137,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Vengeance Hits Home,Furious 7,7.3,4176
1,200000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://www.disney.go.com/cars/,49013,"[{""id"": 830, ""name"": ""car race""}, {""id"": 9663,...",en,Cars 2,Star race car Lightning McQueen and his pal Ma...,49.986590,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-06-11,559852396,106,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Ka-ciao!,Cars 2,5.8,2033
2,170000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""na...",http://marvel.com/guardians,118340,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Guardians of the Galaxy,"Light years from Earth, 26 years after being a...",481.098624,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2014-07-30,773328629,121,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,All heroes start somewhere.,Guardians of the Galaxy,7.9,9742
3,145000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.kungfupanda.com/,140300,"[{""id"": 478, ""name"": ""china""}, {""id"": 779, ""na...",en,Kung Fu Panda 3,"Continuing his ""legendary adventures of awesom...",56.747978,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""CN"", ""name"": ""China""}, {""iso_...",2016-01-23,521170825,95,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Grab destiny by the rice dumplings.,Kung Fu Panda 3,6.7,1603
4,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
5,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

# content based filtering

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tfidf = TfidfVectorizer(stop_words='english')

movies['overview'] = movies['overview'].fillna('')

In [28]:
tfidf_matrix = tfidf.fit_transform(movies['overview'])

In [30]:
pandas.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

,26,abducted,accuser,adventure,adventures,assumes,attorney,awesomeness,bane,barsoom,...,terrorist,threats,toretto,transported,villainous,wanted,war,weary,world,years
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.333333,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.190097,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.155883,0.000000
2,0.237761,0.237761,0.237761,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.237761,0.000000,0.000000,0.000000,0.389934
3,0.000000,0.000000,0.000000,0.000000,0.270444,0.00000,0.000000,0.270444,0.00000,0.000000,...,0.00000,0.270444,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.13565,0.271301,0.000000,0.13565,0.000000,...,0.13565,0.000000,0.000000,0.000000,0.13565,0.000000,0.000000,0.000000,0.000000,0.111235
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.353458,...,0.00000,0.000000,0.000000,0.176729,0.00000,0.000000,0.176729,0.176729,0.144920,0.000000

### Similarity Matrix

In [31]:
from sklearn.metrics.pairwise import linear_kernel
similarity_matrix = linear_kernel(tfidf_matrix, tfidf_matrix)

In [32]:
similarity_matrix

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.02259057],
       [0.        , 0.        , 1.        , 0.        , 0.0433744 ,
        0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.03213867],
       [0.        , 0.        , 0.0433744 , 0.        , 1.        ,
        0.01612024],
       [0.        , 0.02259057, 0.        , 0.03213867, 0.01612024,
        1.        ]])

## similar movies

In [35]:
movie_title = "John Carter"

In [37]:
idx = movies.loc[movies['title'] == movie_title].index[0]
idx

np.int64(5)

In [39]:
scores = list(enumerate(similarity_matrix[idx]))
scores

[(0, np.float64(0.0)),
 (1, np.float64(0.02259056579532686)),
 (2, np.float64(0.0)),
 (3, np.float64(0.032138674066915646)),
 (4, np.float64(0.016120240648257757)),
 (5, np.float64(1.0000000000000007))]

In [41]:
scores = sorted(scores, reverse=True, key=lambda x: x[1])

In [42]:
movies_indices = [tpl[0] for tpl in scores[1:4]]

In [45]:
list(movies["title"].iloc[movies_indices])

['Kung Fu Panda 3', 'Cars 2', 'The Dark Knight Rises']

In [46]:
def similar_movies(movie_title, nr_movies):
    idx = movies.loc[movies['title'] == movie_title].index[0]
    scores = list(enumerate(similarity_matrix[idx]))
    scores = sorted(scores, reverse=True, key=lambda x: x[1])
    movies_indices = [tpl[0] for tpl in scores[1:nr_movies+1]]
    similar_titles = list(movies["title"].iloc[movies_indices])
    return similar_titles

In [49]:
similar_movies("Cars 2", 2)

['John Carter', 'Furious 7']